import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { ThirdwebProvider } from "./thirdweb"
import { createThirdwebClient } from "thirdweb"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Next ThirdWeb DAO",
  description: "Generated by create next app",
}

const client = createThirdwebClient({
  clientId: process.env.NEXT_PUBLIC_THIRDWEB_CLIENT_ID!,
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <ThirdwebProvider client={client}>
        <body className={inter.className}>{children}</body>
      </ThirdwebProvider>
    </html>
  )
}
